### ISSUE TITLE
Can't load a saved preset

### ISSUE THREAD

**Issue by nicolo-faedi** [p3r7/m4l-microkorg-editor#1]
Hello! I've successfully connect my microkorg to the editor and i've saved a preset. 
I saved the preset with the "Save" button and then try to open it with the "Browse".

![1](https://user-images.githubusercontent.com/7045662/132676239-7d22631f-5454-47cc-949f-c7712eeb634a.png)

Immediatly after saving, the preset name keeps <UNTITLED>.
![2](https://user-images.githubusercontent.com/7045662/132676257-692346c8-0313-4d6a-b70a-af1099d7bbc7.png)

And clicking in "LOAD" the presets seems unselectable from the file browse
![3](https://user-images.githubusercontent.com/7045662/132676273-dad9c23a-31d0-489b-839b-16cd998b7d3d.png)

**Comment by nicolo-faedi** [comment]
Solved! File browse doesn't automatically add the .midi extension, so it doesn't reconize the file type.
Just added the ".midi" at the end of the file name, everything works fine!

**Comment by p3r7** [comment]
Ah yes, I can influence the file browser to limit the file extensions shown in the dropdown menu but sadly by default no extension is selected.

Glad you got it worked out.
